### ISSUE TITLE
any tips on how to solve this problem?

### ISSUE THREAD

**Issue by Wcisang** [micHar/kmm-dependency-issues#1]
Hello, I am doing a study on annotation processor with KMM. But I have this same dependency problem. Is there a fix for this problem or a way around it?

I've tried to import the KMM module by configuration but failed
`implementation(project(path = ":annotations", configuration = "jvmDefault"))`

Now I'm out of ideas to do this implementation

**Comment by micHar** [comment]
Take a look here: https://github.com/FutureMind/koru/blob/master/koru-processor/build.gradle.kts

Basically instead of making the processor a pure jvm module, I made it a multiplatform module - I just only use jvm. Works perfectly fine, although I plan to get rid of this as soon as this issue is fixed.

**Comment by micHar** [comment]
You can also take a look here and possibly star the Youtrack issue that's posted there: https://stackoverflow.com/questions/65830632/cant-access-commonmain-multiplatform-classes-from-a-jvm-only-module

**Comment by Wcisang** [comment]
Thanks for the help! i`ll try
